[workspace]
name = "example-package"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = ">=3.10,<3.14"

[environments]
default = { solve-group = "default" }
