// Generated from harness.toml and its declared component TOML files.
// Do not edit this file directly. Run `npm run generate:hcp-sources`.

import * as brandDescriptor from "../../brand/descriptor/HcpMagnet.ts";
import * as brand from "../../brand/HcpServer.ts";
import * as compaction from "../../compaction/HcpServer.ts";
import * as compactionPi from "../../compaction/pi/HcpMagnet.ts";
import * as context from "../../context/HcpServer.ts";
import * as contextMagenta from "../../context/magenta/HcpMagnet.ts";
import * as hooks from "../../hooks/HcpServer.ts";
import * as hooksMagenta from "../../hooks/magenta/HcpMagnet.ts";
import * as memory from "../../memory/HcpServer.ts";
import * as memoryMagenta from "../../memory/magenta/HcpMagnet.ts";
import * as multiagent from "../../multiagent/HcpServer.ts";
import * as multiagentWorkflowMagenta from "../../multiagent/workflow/magenta/HcpMagnet.ts";
import * as policy from "../../policy/HcpServer.ts";
import * as policyMagenta from "../../policy/magenta/HcpMagnet.ts";
import * as promptTemplatesDescriptor from "../../prompt-templates/descriptor/HcpMagnet.ts";
import * as promptTemplates from "../../prompt-templates/HcpServer.ts";
import * as promptTemplatesPi from "../../prompt-templates/pi/HcpMagnet.ts";
import * as runtime from "../../runtime/HcpServer.ts";
import * as runtimeMagenta from "../../runtime/magenta/HcpMagnet.ts";
import * as sandbox from "../../sandbox/HcpServer.ts";
import * as sandboxMagenta from "../../sandbox/magenta/HcpMagnet.ts";
import * as skillsDescriptor from "../../skills/descriptor/HcpMagnet.ts";
import * as skills from "../../skills/HcpServer.ts";
import * as skillsPaperAnalysis from "../../skills/paper-analysis/HcpServer.ts";
import * as skillsPaperAnalysisPi from "../../skills/paper-analysis/pi/HcpMagnet.ts";
import * as skillsPptx from "../../skills/pptx/HcpServer.ts";
import * as skillsPptxPi from "../../skills/pptx/pi/HcpMagnet.ts";
import * as skillsResearchOrchestration from "../../skills/research-orchestration/HcpServer.ts";
import * as skillsResearchOrchestrationPi from "../../skills/research-orchestration/pi/HcpMagnet.ts";
import * as skillsSelfEvo from "../../skills/self-evo/HcpServer.ts";
import * as skillsSelfEvoMagenta from "../../skills/self-evo/magenta/HcpMagnet.ts";
import * as systemPromptDescriptor from "../../system-prompt/descriptor/HcpMagnet.ts";
import * as systemPrompt from "../../system-prompt/HcpServer.ts";
import * as systemPromptPi from "../../system-prompt/pi/HcpMagnet.ts";
import * as themesDescriptor from "../../themes/descriptor/HcpMagnet.ts";
import * as themes from "../../themes/HcpServer.ts";
import * as toolsBash from "../../tools/bash/HcpServer.ts";
import * as toolsBashMagenta from "../../tools/bash/magenta/HcpMagnet.ts";
import * as toolsBashPi from "../../tools/bash/pi/HcpMagnet.ts";
import * as toolsDescriptor from "../../tools/descriptor/HcpMagnet.ts";
import * as toolsEdit from "../../tools/edit/HcpServer.ts";
import * as toolsEditMagenta from "../../tools/edit/magenta/HcpMagnet.ts";
import * as toolsEditPi from "../../tools/edit/pi/HcpMagnet.ts";
import * as toolsFind from "../../tools/find/HcpServer.ts";
import * as toolsFindMagenta from "../../tools/find/magenta/HcpMagnet.ts";
import * as toolsFindPi from "../../tools/find/pi/HcpMagnet.ts";
import * as toolsGrep from "../../tools/grep/HcpServer.ts";
import * as toolsGrepMagenta from "../../tools/grep/magenta/HcpMagnet.ts";
import * as toolsGrepPi from "../../tools/grep/pi/HcpMagnet.ts";
import * as tools from "../../tools/HcpServer.ts";
import * as toolsLs from "../../tools/ls/HcpServer.ts";
import * as toolsLsMagenta from "../../tools/ls/magenta/HcpMagnet.ts";
import * as toolsLsPi from "../../tools/ls/pi/HcpMagnet.ts";
import * as toolsLsp from "../../tools/lsp/HcpServer.ts";
import * as toolsLspMagenta from "../../tools/lsp/magenta/HcpMagnet.ts";
import * as toolsRead from "../../tools/read/HcpServer.ts";
import * as toolsReadMagenta from "../../tools/read/magenta/HcpMagnet.ts";
import * as toolsReadPi from "../../tools/read/pi/HcpMagnet.ts";
import * as toolsShow from "../../tools/show/HcpServer.ts";
import * as toolsShowPi from "../../tools/show/pi/HcpMagnet.ts";
import * as toolsTodo from "../../tools/todo/HcpServer.ts";
import * as toolsTodoPi from "../../tools/todo/pi/HcpMagnet.ts";
import * as toolsToolSearch from "../../tools/tool-search/HcpServer.ts";
import * as toolsToolSearchPi from "../../tools/tool-search/pi/HcpMagnet.ts";
import * as toolsWebFetch from "../../tools/web-fetch/HcpServer.ts";
import * as toolsWebFetchMagenta from "../../tools/web-fetch/magenta/HcpMagnet.ts";
import * as toolsWebSearch from "../../tools/web-search/HcpServer.ts";
import * as toolsWebSearchMagenta from "../../tools/web-search/magenta/HcpMagnet.ts";
import * as toolsWrite from "../../tools/write/HcpServer.ts";
import * as toolsWriteMagenta from "../../tools/write/magenta/HcpMagnet.ts";
import * as toolsWritePi from "../../tools/write/pi/HcpMagnet.ts";
import type { HcpMagnetBuildContext } from "../HcpMagnetTypes.ts";

type HcpServerclass = new () => { readonly moduleName: string; readonly description?: string };
type HcpMagnetclass = {
	readonly module: string;
	readonly kind: string;
	readonly source: string;
	readonly build: (context: HcpMagnetBuildContext) => unknown | Promise<unknown>;
};
type HcpMagnetentry = {
	readonly module: string;
	readonly kind: string;
	readonly name: string;
	readonly product: "tool" | "capability" | "resource";
	readonly source: string;
	readonly selected: boolean;
	readonly autoload: boolean;
	readonly hotSwappable: boolean;
	readonly descriptorPath: string;
	readonly slot?: string;
	readonly requires: readonly string[];
	readonly HcpMagnet: HcpMagnetclass;
};

export const HCP_SERVERS: ReadonlyMap<string, HcpServerclass> = new Map<string, HcpServerclass>([
	["brand", brand.HcpServer],
	["compaction", compaction.HcpServer],
	["context", context.HcpServer],
	["hooks", hooks.HcpServer],
	["memory", memory.HcpServer],
	["multiagent", multiagent.HcpServer],
	["policy", policy.HcpServer],
	["prompt-templates", promptTemplates.HcpServer],
	["runtime", runtime.HcpServer],
	["sandbox", sandbox.HcpServer],
	["skills", skills.HcpServer],
	["skills/paper-analysis", skillsPaperAnalysis.HcpServer],
	["skills/pptx", skillsPptx.HcpServer],
	["skills/research-orchestration", skillsResearchOrchestration.HcpServer],
	["skills/self-evo", skillsSelfEvo.HcpServer],
	["system-prompt", systemPrompt.HcpServer],
	["themes", themes.HcpServer],
	["tools", tools.HcpServer],
	["tools/bash", toolsBash.HcpServer],
	["tools/edit", toolsEdit.HcpServer],
	["tools/find", toolsFind.HcpServer],
	["tools/grep", toolsGrep.HcpServer],
	["tools/ls", toolsLs.HcpServer],
	["tools/lsp", toolsLsp.HcpServer],
	["tools/read", toolsRead.HcpServer],
	["tools/show", toolsShow.HcpServer],
	["tools/todo", toolsTodo.HcpServer],
	["tools/tool-search", toolsToolSearch.HcpServer],
	["tools/web-fetch", toolsWebFetch.HcpServer],
	["tools/web-search", toolsWebSearch.HcpServer],
	["tools/write", toolsWrite.HcpServer],
]);

export const HCP_MAGNETS: readonly HcpMagnetentry[] = [
	{
		module: "compaction",
		kind: "compaction",
		name: "compaction",
		product: "capability",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "compaction/compaction.toml",
		slot: "compaction",
		requires: [],
		HcpMagnet: compactionPi.HcpMagnet,
	},
	{
		module: "context",
		kind: "context",
		name: "workspace",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "context/context.toml",
		slot: "context",
		requires: [],
		HcpMagnet: contextMagenta.HcpMagnet,
	},
	{
		module: "tools",
		kind: "tool",
		name: "tools",
		product: "tool",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: [],
		HcpMagnet: toolsDescriptor.HcpMagnet,
	},
	{
		module: "skills",
		kind: "skill",
		name: "skills",
		product: "resource",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: [],
		HcpMagnet: skillsDescriptor.HcpMagnet,
	},
	{
		module: "prompt-templates",
		kind: "prompt-template",
		name: "descriptor",
		product: "resource",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: [],
		HcpMagnet: promptTemplatesDescriptor.HcpMagnet,
	},
	{
		module: "system-prompt",
		kind: "system-prompt",
		name: "descriptor",
		product: "resource",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: ["system-prompt"],
		HcpMagnet: systemPromptDescriptor.HcpMagnet,
	},
	{
		module: "themes",
		kind: "theme",
		name: "themes",
		product: "resource",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: [],
		HcpMagnet: themesDescriptor.HcpMagnet,
	},
	{
		module: "brand",
		kind: "brand",
		name: "brand",
		product: "resource",
		source: "descriptor",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "harness.toml",
		requires: [],
		HcpMagnet: brandDescriptor.HcpMagnet,
	},
	{
		module: "hooks",
		kind: "hook",
		name: "hooks",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "hooks/hooks.toml",
		slot: "hook",
		requires: ["policy", "sandbox"],
		HcpMagnet: hooksMagenta.HcpMagnet,
	},
	{
		module: "memory",
		kind: "memory",
		name: "memory",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "memory/memory.toml",
		slot: "memory",
		requires: [],
		HcpMagnet: memoryMagenta.HcpMagnet,
	},
	{
		module: "multiagent",
		kind: "multiagent",
		name: "multiagent",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "multiagent/multiagent.toml",
		slot: "multiagent",
		requires: [],
		HcpMagnet: multiagentWorkflowMagenta.HcpMagnet,
	},
	{
		module: "policy",
		kind: "policy",
		name: "policy",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "policy/policy.toml",
		slot: "policy",
		requires: [],
		HcpMagnet: policyMagenta.HcpMagnet,
	},
	{
		module: "prompt-templates",
		kind: "prompt-template",
		name: "prompt-templates",
		product: "capability",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "prompt-templates/prompt-templates.toml",
		slot: "prompt-template",
		requires: [],
		HcpMagnet: promptTemplatesPi.HcpMagnet,
	},
	{
		module: "runtime",
		kind: "runtime",
		name: "process",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "runtime/runtime.toml",
		slot: "runtime:process",
		requires: [],
		HcpMagnet: runtimeMagenta.HcpMagnet,
	},
	{
		module: "runtime",
		kind: "runtime",
		name: "script-runtimes",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "runtime/script-runtimes.toml",
		slot: "runtime:script-runtimes",
		requires: ["runtime:process"],
		HcpMagnet: runtimeMagenta.HcpMagnet,
	},
	{
		module: "sandbox",
		kind: "sandbox",
		name: "sandbox",
		product: "capability",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "sandbox/sandbox.toml",
		slot: "sandbox",
		requires: [],
		HcpMagnet: sandboxMagenta.HcpMagnet,
	},
	{
		module: "skills/paper-analysis",
		kind: "skill",
		name: "paper-analysis",
		product: "resource",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "skills/paper-analysis/paper-analysis.toml",
		requires: [],
		HcpMagnet: skillsPaperAnalysisPi.HcpMagnet,
	},
	{
		module: "skills/pptx",
		kind: "skill",
		name: "pptx",
		product: "resource",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "skills/pptx/pptx.toml",
		requires: [],
		HcpMagnet: skillsPptxPi.HcpMagnet,
	},
	{
		module: "skills/research-orchestration",
		kind: "skill",
		name: "research-orchestration",
		product: "resource",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "skills/research-orchestration/research-orchestration.toml",
		requires: [],
		HcpMagnet: skillsResearchOrchestrationPi.HcpMagnet,
	},
	{
		module: "skills/self-evo",
		kind: "skill",
		name: "self-evo",
		product: "resource",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "skills/self-evo/self-evo.toml",
		requires: [],
		HcpMagnet: skillsSelfEvoMagenta.HcpMagnet,
	},
	{
		module: "system-prompt",
		kind: "system-prompt",
		name: "system-prompt",
		product: "capability",
		source: "pi",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "system-prompt/system-prompt.toml",
		slot: "system-prompt",
		requires: [],
		HcpMagnet: systemPromptPi.HcpMagnet,
	},
	{
		module: "tools/bash",
		kind: "tool",
		name: "bash",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/bash/bash.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsBashMagenta.HcpMagnet,
	},
	{
		module: "tools/bash",
		kind: "tool",
		name: "bash",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/bash/bash.toml",
		requires: [],
		HcpMagnet: toolsBashPi.HcpMagnet,
	},
	{
		module: "tools/edit",
		kind: "tool",
		name: "edit",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/edit/edit.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsEditMagenta.HcpMagnet,
	},
	{
		module: "tools/edit",
		kind: "tool",
		name: "edit",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/edit/edit.toml",
		requires: [],
		HcpMagnet: toolsEditPi.HcpMagnet,
	},
	{
		module: "tools/find",
		kind: "tool",
		name: "find",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/find/find.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsFindMagenta.HcpMagnet,
	},
	{
		module: "tools/find",
		kind: "tool",
		name: "find",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/find/find.toml",
		requires: [],
		HcpMagnet: toolsFindPi.HcpMagnet,
	},
	{
		module: "tools/grep",
		kind: "tool",
		name: "grep",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/grep/grep.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsGrepMagenta.HcpMagnet,
	},
	{
		module: "tools/grep",
		kind: "tool",
		name: "grep",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/grep/grep.toml",
		requires: [],
		HcpMagnet: toolsGrepPi.HcpMagnet,
	},
	{
		module: "tools/ls",
		kind: "tool",
		name: "ls",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/ls/ls.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsLsMagenta.HcpMagnet,
	},
	{
		module: "tools/ls",
		kind: "tool",
		name: "ls",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/ls/ls.toml",
		requires: [],
		HcpMagnet: toolsLsPi.HcpMagnet,
	},
	{
		module: "tools/lsp",
		kind: "tool",
		name: "lsp",
		product: "tool",
		source: "magenta",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/lsp/lsp.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsLspMagenta.HcpMagnet,
	},
	{
		module: "tools/read",
		kind: "tool",
		name: "read",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/read/read.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsReadMagenta.HcpMagnet,
	},
	{
		module: "tools/read",
		kind: "tool",
		name: "read",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/read/read.toml",
		requires: [],
		HcpMagnet: toolsReadPi.HcpMagnet,
	},
	{
		module: "tools/show",
		kind: "tool",
		name: "show",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/show/show.toml",
		requires: [],
		HcpMagnet: toolsShowPi.HcpMagnet,
	},
	{
		module: "tools/todo",
		kind: "tool",
		name: "todo",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/todo/todo.toml",
		requires: [],
		HcpMagnet: toolsTodoPi.HcpMagnet,
	},
	{
		module: "tools/tool-search",
		kind: "tool",
		name: "tool-search",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/tool-search/tool-search.toml",
		requires: [],
		HcpMagnet: toolsToolSearchPi.HcpMagnet,
	},
	{
		module: "tools/web-fetch",
		kind: "tool",
		name: "web-fetch",
		product: "tool",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "tools/web-fetch/web-fetch.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsWebFetchMagenta.HcpMagnet,
	},
	{
		module: "tools/web-search",
		kind: "tool",
		name: "web-search",
		product: "tool",
		source: "magenta",
		selected: true,
		autoload: true,
		hotSwappable: false,
		descriptorPath: "tools/web-search/web-search.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsWebSearchMagenta.HcpMagnet,
	},
	{
		module: "tools/write",
		kind: "tool",
		name: "write",
		product: "tool",
		source: "magenta",
		selected: false,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/write/write.toml",
		requires: ["runtime:process", "sandbox"],
		HcpMagnet: toolsWriteMagenta.HcpMagnet,
	},
	{
		module: "tools/write",
		kind: "tool",
		name: "write",
		product: "tool",
		source: "pi",
		selected: true,
		autoload: false,
		hotSwappable: false,
		descriptorPath: "tools/write/write.toml",
		requires: [],
		HcpMagnet: toolsWritePi.HcpMagnet,
	},
];
