export {
	DEFAULT_PEER_MESSAGE_DRAIN_CAP,
	formatPeerMessages,
	MAX_PEER_MESSAGE_BATCH_BYTES,
	MAX_PEER_MESSAGE_CONTENT_BYTES,
	PEER_MESSAGE_CUSTOM_TYPE,
	type PeerMessageDetails as HcpPeerMessageDetails,
	type RecipientPresence,
	SendMessageController,
	type SendMessageControllerDeps,
	type SendMessageInput,
	sendMessageSchema,
	type WakeDisposition,
	wrapPeerMessageForLlm,
} from "@magenta/harness";
