/**
 * Generated brand version - DO NOT EDIT
 * Generated by scripts/generate-brand-version.mjs
 * Active brand: magenta
 */

export const BRAND_VERSION = "0.0.19";
export const BRAND_NAME = "Magenta";
